language: go
sudo: false
go:
  - 1.4

before_install:
  - go get golang.org/x/tools/cmd/vet
  #- go get code.google.com/p/go.tools/cmd/cover
  #- go get golang.org/x/lint/golint
  #- go get github.com/mattn/goveralls
  
install:
    - go get -d -v ./... && go build -v ./...

script:
  - go vet -x ./...
  #- $HOME/gopath/bin/golint ./...
  - go test -v ./...
  #- go test -covermode=count -coverprofile=profile.cov .

#after_script:
  #- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
